import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../utils/api';
import { useToast } from '../context/ToastContext';
import { 
  Plus, Search, Edit3, Trash2, Eye, FileText, 
  Loader2, AlertCircle, Calendar, CalendarDays, X,
  Sparkles, Share2
} from 'lucide-react';

const Dashboard = () => {
  const [resumes, setResumes] = useState([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [createLoading, setCreateLoading] = useState(false);
  const [createMode, setCreateMode] = useState('blank'); // 'blank' | 'ai' | 'prompt'
  const [rawResumeText, setRawResumeText] = useState('');
  const [promptProfession, setPromptProfession] = useState('');
  const [promptExpLevel, setPromptExpLevel] = useState('Mid-level');
  const [promptBackground, setPromptBackground] = useState('');

  const navigate = useNavigate();
  const { showToast } = useToast();

  const fetchResumes = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await api.get('/user/resumes');
      if (response.data?.success) {
        setResumes(response.data.resumes || []);
      } else {
        setResumes(response.data || []);
      }
    } catch (err) {
      console.error('Error fetching resumes:', err);
      // Fallback message
      setError('Could not retrieve resumes from server.');
      showToast('Error loading resumes.', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchResumes();
  }, []);

  const handleCreateResume = async (e) => {
    e.preventDefault();
    if (!newTitle.trim()) {
      showToast('Please enter a resume title.', 'warning');
      return;
    }

    setCreateLoading(true);
    try {
      let resumeId;
      if (createMode === 'blank') {
        const response = await api.post('/resumes/create', { title: newTitle });
        resumeId = response.data?.resume?._id;
        showToast('Resume created successfully!', 'success');
      } else if (createMode === 'ai') {
        if (!rawResumeText.trim()) {
          showToast('Please paste your existing resume text to parse.', 'warning');
          setCreateLoading(false);
          return;
        }
        const response = await api.post('/ai/upload-resume', {
          title: newTitle,
          resumeText: rawResumeText,
        });
        resumeId = response.data?.resumeId;
        showToast('AI parser completed! Opening builder...', 'success');
      } else if (createMode === 'prompt') {
        if (!promptProfession.trim()) {
          showToast('Please enter a profession target.', 'warning');
          setCreateLoading(false);
          return;
        }
        const response = await api.post('/ai/generate-resume-prompt', {
          title: newTitle,
          profession: promptProfession,
          experienceLevel: promptExpLevel,
          briefBackground: promptBackground,
        });
        resumeId = response.data?.resumeId;
        showToast('Resume generated by AI! Opening builder...', 'success');
      }

      setIsModalOpen(false);
      setNewTitle('');
      setRawResumeText('');
      setPromptProfession('');
      setPromptBackground('');
      setPromptExpLevel('Mid-level');
      setCreateMode('blank');

      if (resumeId) {
        navigate(`/app/builder/${resumeId}`);
      } else {
        fetchResumes();
      }
    } catch (err) {
      console.error('Error creating resume:', err);
      showToast(err.response?.data?.message || 'Failed to create resume.', 'error');
    } finally {
      setCreateLoading(false);
    }
  };

  const handleDeleteResume = async (id) => {
    if (!window.confirm('Are you sure you want to delete this resume? This action cannot be undone.')) {
      return;
    }

    try {
      await api.delete(`/resumes/delete/${id}`);
      showToast('Resume deleted successfully!', 'success');
      setResumes((prev) => prev.filter((r) => r._id !== id));
    } catch (err) {
      console.error('Error deleting resume:', err);
      showToast('Failed to delete resume.', 'error');
    }
  };

  // Filter resumes based on search query
  const filteredResumes = resumes.filter((resume) =>
    resume.title?.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-8">
      {/* Header section */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-8">
        <div>
          <h1 className="text-3xl font-bold text-slate-800 tracking-tight">My Resumes</h1>
          <p className="text-slate-500 mt-1">Manage, edit, and create your AI-enhanced resumes.</p>
        </div>
        
        <button
          onClick={() => setIsModalOpen(true)}
          className="flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-orange-600 hover:bg-orange-700 text-white font-semibold shadow-md shadow-orange-600/10 transition cursor-pointer text-sm"
        >
          <Plus className="w-5 h-5" />
          <span>Create New Resume</span>
        </button>
      </div>

      {/* Search and Filters */}
      <div className="bg-white rounded-xl border border-slate-100 p-4 mb-8 shadow-sm flex items-center gap-3">
        <Search className="w-5 h-5 text-slate-400 shrink-0" />
        <input
          type="text"
          placeholder="Search by resume title..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="w-full text-slate-700 bg-transparent border-none outline-none text-sm placeholder-slate-400"
        />
        {searchQuery && (
          <button 
            onClick={() => setSearchQuery('')}
            className="p-1 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition"
          >
            <X className="w-4 h-4" />
          </button>
        )}
      </div>

      {/* Resumes Grid */}
      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {[1, 2, 3].map((n) => (
            <div key={n} className="bg-white rounded-2xl border border-slate-100 p-6 h-52 animate-pulse flex flex-col justify-between">
              <div>
                <div className="h-6 bg-slate-200 rounded w-2/3 mb-2"></div>
                <div className="h-4 bg-slate-100 rounded w-1/3"></div>
              </div>
              <div className="h-10 bg-slate-100 rounded w-full"></div>
            </div>
          ))}
        </div>
      ) : error ? (
        <div className="flex flex-col items-center justify-center py-16 bg-white border border-dashed border-slate-200 rounded-2xl">
          <AlertCircle className="w-12 h-12 text-slate-400 mb-4" />
          <h3 className="text-lg font-semibold text-slate-700 mb-1">Server Connection Issue</h3>
          <p className="text-slate-500 text-sm max-w-md text-center mb-6">{error}</p>
          <button
            onClick={fetchResumes}
            className="px-4 py-2 bg-orange-100 hover:bg-orange-200 text-orange-700 rounded-lg text-sm font-semibold transition"
          >
            Retry Connection
          </button>
        </div>
      ) : filteredResumes.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 bg-white border border-dashed border-slate-200 rounded-2xl">
          <FileText className="w-16 h-16 text-slate-300 mb-4" />
          <h3 className="text-xl font-bold text-slate-700 mb-1">No resumes found</h3>
          <p className="text-slate-500 text-sm max-w-sm text-center mb-6">
            {searchQuery 
              ? `No resumes match "${searchQuery}". Try a different search.`
              : "Get started by creating your first AI-enhanced resume."}
          </p>
          {!searchQuery && (
            <button
              onClick={() => setIsModalOpen(true)}
              className="px-5 py-2.5 bg-orange-600 hover:bg-orange-700 text-white rounded-xl text-sm font-semibold transition cursor-pointer"
            >
              Build your first resume
            </button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredResumes.map((resume) => (
            <div 
              key={resume._id} 
              className="group bg-white rounded-2xl border border-slate-100 p-6 shadow-sm hover:shadow-md hover:border-orange-200 transition-all flex flex-col justify-between"
            >
              <div>
                <div className="flex justify-between items-start gap-2 mb-3">
                  <h3 className="text-lg font-bold text-slate-800 group-hover:text-orange-600 transition truncate">
                    {resume.title || 'Untitled Resume'}
                  </h3>
                  <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold uppercase tracking-wider ${
                    resume.public 
                      ? 'bg-emerald-50 text-emerald-600 border border-emerald-100' 
                      : 'bg-slate-100 text-slate-500 border border-slate-200'
                  }`}>
                    {resume.public ? 'Public' : 'Private'}
                  </span>
                </div>
                
                <div className="space-y-2 text-slate-500 text-xs mb-6">
                  <p className="flex items-center gap-1.5">
                    <FileText className="w-3.5 h-3.5" />
                    <span>Template: <span className="font-semibold text-slate-700">{resume.template || 'Classic'}</span></span>
                  </p>
                  <p className="flex items-center gap-1.5">
                    <CalendarDays className="w-3.5 h-3.5" />
                    <span>Updated: <span className="text-slate-600">{new Date(resume.updatedAt).toLocaleDateString()}</span></span>
                  </p>
                </div>
              </div>

              <div className="flex items-center justify-between border-t border-slate-50 pt-4 gap-2">
                <button
                  onClick={() => navigate(`/app/builder/${resume._id}`)}
                  className="flex-1 flex items-center justify-center gap-1.5 py-2 px-3 rounded-lg bg-orange-50 hover:bg-orange-100 text-orange-700 font-semibold text-xs transition cursor-pointer"
                >
                  <Edit3 className="w-3.5 h-3.5" />
                  <span>Edit</span>
                </button>
                
                <button
                  onClick={() => navigate(`/app/view/${resume._id}`)}
                  className="p-2 rounded-lg border border-slate-200 text-slate-500 hover:text-slate-700 hover:bg-slate-50 transition cursor-pointer"
                  title="Preview & Share"
                >
                  <Eye className="w-4 h-4" />
                </button>

                <button
                  onClick={() => handleDeleteResume(resume._id)}
                  className="p-2 rounded-lg border border-rose-100 text-rose-500 hover:text-rose-700 hover:bg-rose-50/50 transition cursor-pointer"
                  title="Delete Resume"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Create Resume Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-md overflow-hidden border border-slate-100 animate-scale-up">
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
              <h3 className="font-bold text-slate-800 text-lg">Create New Resume</h3>
              <button 
                onClick={() => {
                  setIsModalOpen(false);
                  setNewTitle('');
                  setRawResumeText('');
                  setPromptProfession('');
                  setPromptBackground('');
                  setPromptExpLevel('Mid-level');
                  setCreateMode('blank');
                }}
                className="p-1 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <form onSubmit={handleCreateResume} className="p-6 space-y-4">
              <div>
                <label className="block text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">
                  Resume Title
                </label>
                <input
                  type="text"
                  placeholder="e.g. Software Engineer Resume"
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl border border-slate-200 focus:border-orange-500 focus:ring-2 focus:ring-orange-200 outline-none text-slate-800 text-sm bg-slate-55"
                  required
                  autoFocus
                />
              </div>

              {/* Mode Select Tabs */}
              <div className="grid grid-cols-3 gap-2.5 pt-2">
                <button
                  type="button"
                  onClick={() => setCreateMode('blank')}
                  className={`flex flex-col items-center justify-center p-3 rounded-xl border text-center transition cursor-pointer ${
                    createMode === 'blank'
                      ? 'border-orange-500 bg-orange-50/20 text-orange-600 font-bold shadow-sm'
                      : 'border-slate-200 hover:bg-slate-50 text-slate-650'
                  }`}
                >
                  <Plus className="w-5 h-5 mb-1" />
                  <span className="text-[10px] font-semibold">Blank Form</span>
                </button>

                <button
                  type="button"
                  onClick={() => setCreateMode('ai')}
                  className={`flex flex-col items-center justify-center p-3 rounded-xl border text-center transition cursor-pointer ${
                    createMode === 'ai'
                      ? 'border-orange-500 bg-orange-50/20 text-orange-600 font-bold shadow-sm'
                      : 'border-slate-200 hover:bg-slate-50 text-slate-650'
                  }`}
                >
                  <Share2 className="w-5 h-5 mb-1" />
                  <span className="text-[10px] font-semibold">AI Parse Upload</span>
                </button>

                <button
                  type="button"
                  onClick={() => setCreateMode('prompt')}
                  className={`flex flex-col items-center justify-center p-3 rounded-xl border text-center transition cursor-pointer ${
                    createMode === 'prompt'
                      ? 'border-orange-500 bg-orange-50/20 text-orange-600 font-bold shadow-sm'
                      : 'border-slate-200 hover:bg-slate-50 text-slate-650'
                  }`}
                >
                  <Sparkles className="w-5 h-5 mb-1" />
                  <span className="text-[10px] font-semibold">AI Generate (Prompt)</span>
                </button>
              </div>

              {/* AI Parse mode input */}
              {createMode === 'ai' && (
                <div className="space-y-2 pt-2 animate-fade-in">
                  <div className="bg-orange-50 border border-orange-100 rounded-xl p-3 flex gap-2 text-xs text-orange-800">
                    <Sparkles className="shrink-0 mt-0.5 text-orange-600 w-4 h-4" />
                    <p>Paste your existing text details below and the AI parser will split it into structured resume nodes.</p>
                  </div>
                  <textarea
                    rows={5}
                    placeholder="Paste your raw text details here..."
                    value={rawResumeText}
                    onChange={(e) => setRawResumeText(e.target.value)}
                    required
                    className="w-full px-4 py-3 rounded-xl border border-slate-200 outline-none focus:border-orange-500 transition text-xs font-mono bg-slate-50/50"
                  />
                </div>
              )}

              {/* AI Generate Prompt mode inputs */}
              {createMode === 'prompt' && (
                <div className="space-y-3 pt-2 animate-fade-in">
                  <div className="bg-orange-50 border border-orange-100 rounded-xl p-3 flex gap-2 text-xs text-orange-805">
                    <Sparkles className="shrink-0 mt-0.5 text-orange-600 w-4 h-4" />
                    <p>Input your profession targets and key experiences, and our AI will draft a complete starting resume instantly.</p>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div className="space-y-1">
                      <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Profession Target</label>
                      <input
                        type="text"
                        required
                        placeholder="e.g. Backend Developer"
                        value={promptProfession}
                        onChange={(e) => setPromptProfession(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs outline-none focus:border-orange-500 bg-slate-50/50"
                      />
                    </div>
                    
                    <div className="space-y-1">
                      <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Experience Level</label>
                      <select
                        value={promptExpLevel}
                        onChange={(e) => setPromptExpLevel(e.target.value)}
                        className="w-full px-3 py-2 rounded-xl border border-slate-200 text-xs outline-none focus:border-orange-500 bg-white"
                      >
                        <option value="Entry-level">Entry-level</option>
                        <option value="Mid-level">Mid-level</option>
                        <option value="Senior-level">Senior-level</option>
                      </select>
                    </div>
                  </div>

                  <div className="space-y-1">
                    <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Background Summary & Focus (Optional)</label>
                    <textarea
                      rows={3}
                      placeholder="e.g. 4 years of JavaScript/Python. Built cloud databases and REST APIs."
                      value={promptBackground}
                      onChange={(e) => setPromptBackground(e.target.value)}
                      className="w-full px-3 py-2.5 rounded-xl border border-slate-200 text-xs outline-none focus:border-orange-500 bg-slate-50/50"
                    />
                  </div>
                </div>
              )}

              <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => {
                    setIsModalOpen(false);
                    setNewTitle('');
                    setRawResumeText('');
                    setPromptProfession('');
                    setPromptBackground('');
                    setPromptExpLevel('Mid-level');
                    setCreateMode('blank');
                  }}
                  className="px-4 py-2.5 rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50 transition text-sm font-semibold cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={createLoading}
                  className="flex items-center gap-1.5 px-5 py-2.5 rounded-xl bg-orange-600 hover:bg-orange-700 text-white font-semibold shadow-md shadow-orange-600/10 transition cursor-pointer text-sm disabled:opacity-75 disabled:cursor-not-allowed"
                >
                  {createLoading ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      <span>{createMode === 'prompt' ? 'Drafting...' : createMode === 'ai' ? 'Parsing...' : 'Creating...'}</span>
                    </>
                  ) : (
                    <>
                      {createMode === 'prompt' ? <Sparkles className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
                      <span>{createMode === 'prompt' ? 'Generate Resume' : createMode === 'ai' ? 'Parse & Open' : 'Create'}</span>
                    </>
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;
